# Generated by Django 3.1.2 on 2020-11-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups_App', '0004_org_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='location',
            field=models.CharField(default='Sears tower', max_length=255),
            preserve_default=False,
        ),
    ]
